---
- name: "Build and deploy a Docker container with Ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: Stop the current running container
      docker_container:
        name: web-container
        state: stopped
      ignore_errors: yes

    - name: Remove the stopped container
      docker_container:
        name: web-container
        state: absent
      ignore_errors: yes

    - name: Remove the existing Docker image
      docker_image:
        name: triple3a/comingsoon-page
        state: absent
      ignore_errors: yes

    - name: Build the Docker image using the Dockerfile
      command: docker build -t triple3a/comingsoon-page .

    - name: Push the Docker image to DockerHub
      command: docker push triple3a/comingsoon-page

    - name: Run the new Docker container
      docker_container:
        name: web-container
        image: triple3a/comingsoon-page
        ports:
          - "5000:80"
        state: started
