- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: Docker login
      command: docker login -u your_username -p your_password
      ignore_errors: yes

    - name: Stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: Remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: Remove comingsoon-image if it exists
      command: docker rmi chaima2024/comingsoon-page
      ignore_errors: yes

    - name: Build docker image using the Dockerfile
      command: docker build -t chaima2024/comingsoon-page .

    - name: Push Image to DockerHub
      command: docker push chaima2024/comingsoon-page

    - name: Run container
      command: docker run -d --name web-container -p 5000:80 chaima2024/comingsoon-page
