---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: remove comingsoon-image
      command: docker rmi chaima2024/comingsoon
      ignore_errors: yes

    - name: load Docker credentials from vault
      ansible.builtin.include_vars:
        file: docker_credentials.yml
        name: docker_creds

    - name: login to Docker Hub
      command: docker login --username "{{ docker_creds.docker_username }}" --password "{{ docker_creds.docker_password }}"
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t chaima2024/comingsoon .

    - name: Push Image to dockerhub
      command: docker push chaima2024/comingsoon

    - name: run container
      command: docker run -d --name web-container -p 5000:80 chaima2024/comingsoon
